# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Téléphone (canonique)')),
                ('display_phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone affiché')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('department', models.CharField(default='FASEG', max_length=120, verbose_name='Faculté / Département')),
                ('program', models.CharField(default='Sciences Économiques', max_length=120, verbose_name='Filière')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=10, verbose_name='Niveau')),
                ('role', models.CharField(choices=[('USER', 'Étudiant'), ('STAFF', 'Enseignant / Staff'), ('SUPERUSER', 'Super Administrateur')], default='USER', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès administration')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super-administrateur')),
                ('is_sponsored', models.BooleanField(default=False, verbose_name='Compte sponsorisé (Accès gratuit total)')),
                ('is_ai_suspended', models.BooleanField(default=False, verbose_name='Accès IA suspendu')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash PBKDF2 (Legacy)')),
                ('password_salt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salt PBKDF2 (Legacy)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Jeton d'authentification",
                'verbose_name_plural': "Jetons d'authentification",
            },
        ),
    ]
