# Generated by Django 6.1.1 on 2026-09-28 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Message / Contenu')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès'), ('alert', 'Alerte Urgente'), ('reminder', 'Rappel Pédagogique')], default='info', max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute / Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('target_type', models.CharField(choices=[('ALL', 'Tous les utilisateurs'), ('USERS', 'Utilisateurs spécifiques'), ('ROLE', 'Par Rôle'), ('DEPARTMENT', 'Par Département / Faculté'), ('LEVEL', 'Par Niveau LMD')], default='ALL', max_length=30, verbose_name='Cible')),
                ('target_role', models.CharField(blank=True, max_length=30, null=True, verbose_name='Rôle ciblé')),
                ('target_department', models.CharField(blank=True, max_length=120, null=True, verbose_name='Département ciblé')),
                ('target_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Niveau ciblé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name="Date & Heure programmée d'envoi")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmé'), ('SENT', 'Envoyé'), ('CANCELLED', 'Annulé')], default='SENT', max_length=20, verbose_name='Statut')),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name="Lien d'action interne")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires ciblés')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipientStatus',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='notifications.notification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'État de lecture',
                'verbose_name_plural': 'États de lecture',
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
