# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du questionnaire')),
                ('description', models.TextField(blank=True, verbose_name='Consignes / Description')),
                ('passing_score_percent', models.IntegerField(default=75, verbose_name='Score de validation (%)')),
            ],
            options={
                'verbose_name': 'Questionnaire interactif',
                'verbose_name_plural': 'Questionnaires interactifs',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_number', models.IntegerField(default=1, verbose_name='Numéro de séance')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, verbose_name='Description brève')),
                ('objective', models.TextField(blank=True, default='Objectif pédagogique de la séance.', verbose_name='Objectifs pédagogiques')),
                ('estimated_minutes', models.IntegerField(default=45, verbose_name='Durée estimée (minutes)')),
                ('order', models.IntegerField(default=1, verbose_name="Ordre dans l'UE")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendue')),
                ('is_locked_for_users', models.BooleanField(blank=True, default=None, null=True, verbose_name='Verrouillée pour étudiants simples')),
                ('summary_text', models.TextField(blank=True, verbose_name='Résumé / Cours écrit')),
                ('video', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées vidéo')),
                ('audio', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées podcast audio')),
                ('pdf', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées support PDF')),
                ('flashcards', models.JSONField(blank=True, default=list, verbose_name='Cartes mémo (Flashcards)')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['order', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('question_type', models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple'), ('boolean', 'Vrai / Faux')], default='single', max_length=20, verbose_name='Type de question')),
                ('options', models.JSONField(default=list, verbose_name='Options de réponse')),
                ('correct_answer', models.JSONField(default=list, verbose_name='Bonne(s) réponse(s)')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication pédagogique de la réponse')),
                ('points', models.IntegerField(default=1, verbose_name='Points attribués')),
                ('order', models.IntegerField(default=1, verbose_name='Ordre de la question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.session', verbose_name='Séance associée'),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Code UE (ex: ECO-101)')),
                ('title', models.CharField(max_length=255, verbose_name="Intitulé de l'UE")),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('objective', models.TextField(blank=True, default="Objectif pédagogique général de l'UE.", verbose_name='Objectifs pédagogiques')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=10, verbose_name='Niveau')),
                ('semester', models.CharField(default='Semestre 1', max_length=50, verbose_name='Semestre')),
                ('academic_year', models.CharField(default='2025-2026', max_length=50, verbose_name='Année académique')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('price_fcfa', models.IntegerField(default=500, verbose_name='Prix en FCFA')),
                ('order', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name="Image d'illustration")),
                ('coefficient', models.IntegerField(default=2, verbose_name='Coefficient')),
                ('credit_ects', models.IntegerField(default=4, verbose_name='Crédits ECTS')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues', to='academic.department', verbose_name='Département')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues', to='academic.program', verbose_name='Filière')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement (UE)",
                'verbose_name_plural': "Unités d'Enseignement (UE)",
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.ue', verbose_name='UE parente'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='Score obtenu')),
                ('max_score', models.IntegerField(verbose_name='Score maximal')),
                ('percentage', models.IntegerField(verbose_name='Pourcentage de réussite')),
                ('passed', models.BooleanField(verbose_name='Test validé')),
                ('user_answers', models.JSONField(default=dict, verbose_name="Réponses de l'étudiant")),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de soumission')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz', verbose_name='Questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session', verbose_name='Séance')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Tentative de questionnaire',
                'verbose_name_plural': 'Tentatives de questionnaire',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Validé / Terminé')], default='not_started', max_length=20, verbose_name="Statut d'avancement")),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernier accès')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session', verbose_name='Séance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Progression séance',
                'verbose_name_plural': 'Progressions séances',
                'unique_together': {('user', 'session')},
            },
        ),
        migrations.CreateModel(
            name='UserUEAccess',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'attribution")),
                ('granted_by', models.CharField(default='system_registration', max_length=100, verbose_name='Accordé par')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('revoked', 'Révoqué')], default='active', max_length=20, verbose_name='Statut')),
                ('is_first_chapter_only', models.BooleanField(default=False, verbose_name='Premier chapitre uniquement')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='courses.ue', verbose_name='UE accordée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Accès UE Étudiant',
                'verbose_name_plural': 'Accès UE Étudiants',
                'unique_together': {('user', 'ue')},
            },
        ),
    ]
