# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ue_price_fcfa', models.IntegerField(default=500, verbose_name='Prix standard par UE (FCFA)')),
                ('discounted_ue_price_fcfa', models.IntegerField(default=300, verbose_name='Prix réduit (dès 3 UE) (FCFA)')),
                ('online_assistance_per_hour_fcfa', models.IntegerField(default=1000, verbose_name='Tutorat en ligne / heure (FCFA)')),
                ('in_person_assistance_per_hour_fcfa', models.IntegerField(default=2000, verbose_name='Tutorat présentiel / heure (FCFA)')),
                ('first_chapter_free_enabled', models.BooleanField(default=True, verbose_name='1ère séance toujours gratuite')),
                ('allow_self_registration', models.BooleanField(default=True, verbose_name="Autoriser l'auto-inscription")),
                ('university_name', models.CharField(default='UL Study Flow (EdTech par les étudiants)', max_length=255, verbose_name="Nom de l'institution")),
                ('academic_year_current', models.CharField(default='2025-2026', max_length=50, verbose_name='Année académique courante')),
                ('contact_phones', models.JSONField(default=list, verbose_name='Numéros de contact / T-Money / Flooz')),
                ('contact_email', models.EmailField(default='ulstudyflow@gmail.com', max_length=254, verbose_name='Email de contact')),
            ],
            options={
                'verbose_name': 'Configuration de la plateforme',
                'verbose_name_plural': 'Configuration de la plateforme',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo (ex: REUSSITE20)')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='Pourcentage de réduction (%)')),
                ('applicable_to', models.CharField(choices=[('all', 'Toutes les prestations'), ('ue_unlock', 'Déblocage UE uniquement'), ('tutoring', 'Assistance tutorat')], default='all', max_length=30, verbose_name='Applicable à')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Code promotionnel',
                'verbose_name_plural': 'Codes promotionnels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnlockRequest',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150, verbose_name='Nom et Prénom')),
                ('user_phone', models.CharField(max_length=50, verbose_name='Numéro de paiement')),
                ('ue_ids', models.JSONField(default=list, verbose_name='IDs des UE demandées')),
                ('ue_codes', models.JSONField(default=list, verbose_name='Codes des UE demandées')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code promo utilisé')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='Réduction appliquée (%)')),
                ('subtotal_fcfa', models.IntegerField(default=0, verbose_name='Sous-total (FCFA)')),
                ('transaction_fee_fcfa', models.IntegerField(default=100, verbose_name='Frais de transaction (FCFA)')),
                ('total_fcfa', models.IntegerField(default=100, verbose_name='Montant total (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée (Accès accordés)'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut de la demande')),
                ('payment_method', models.CharField(default='Mix Togo / Flooz Togo', max_length=100, verbose_name='Moyen de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques / Motif de rejet')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de demande')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'examen")),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Examiné par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Demande de déblocage d'UE",
                'verbose_name_plural': "Demandes de déblocage d'UE",
                'ordering': ['-created_at'],
            },
        ),
    ]
