# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('user_phone', models.CharField(blank=True, max_length=50, verbose_name="Téléphone de l'utilisateur")),
                ('user_role', models.CharField(blank=True, max_length=30, verbose_name="Rôle au moment de l'action")),
                ('action', models.CharField(max_length=100, verbose_name='Action effectuée')),
                ('resource', models.CharField(max_length=100, verbose_name='Ressource concernée')),
                ('details', models.TextField(verbose_name="Détails de l'opération")),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
