# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32, verbose_name='Année académique (ex: 2025-2026)')),
                ('is_current', models.BooleanField(default=False, verbose_name='Année en cours')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivée')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='Sigle / Code (ex: FASEG)')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la Faculté / Département')),
                ('faculty', models.CharField(default='Université de Lomé', max_length=255, verbose_name='Établissement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
            ],
            options={
                'verbose_name': 'Département / Faculté',
                'verbose_name_plural': 'Départements & Facultés',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='Code de la filière')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la filière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Filière de formation',
                'verbose_name_plural': 'Filières de formation',
                'ordering': ['department', 'name'],
            },
        ),
    ]
