# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du formulaire')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('theme_color', models.CharField(default='#075E54', max_length=30, verbose_name='Couleur du thème')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif / Accessible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('fields', models.JSONField(default=list, verbose_name='Champs configurés (JSON)')),
            ],
            options={
                'verbose_name': 'Formulaire dynamique',
                'verbose_name_plural': 'Formulaires dynamiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150, verbose_name="Nom de l'étudiant / visiteur")),
                ('user_phone', models.CharField(max_length=50, verbose_name='Téléphone de contact')),
                ('data', models.JSONField(default=dict, verbose_name='Données soumises (JSON)')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de soumission')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_builder.dynamicform', verbose_name='Formulaire')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Soumission de formulaire',
                'verbose_name_plural': 'Soumissions de formulaires',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
